source 'https://rubygems.org'

gem 'hashie', '~> 2.0.5'
gem 'interpol', :path => '..'
gem 'multi_json', '~> 1.2.0'
gem 'nokogiri', '~> 1.6.0'
gem 'rake', '~> 0.9.2.2'
gem 'rspec', '~> 2.9'
gem 'sinatra', '~> 1.3'

